[build]
  command = ""
  publish = "public"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "http://*"
  to = "https://isaacwalsham.com/:splat"
  status = 301
  force = true